// Keep existing API country values stable; English labels are presentation only.
export const countries = [
  { value: "Afganistán", iso: 'AF', label: "Afghanistan" },
  { value: "Albania", iso: 'AL', label: "Albania" },
  { value: "Argelia", iso: 'DZ', label: "Algeria" },
  { value: "Andorra", iso: 'AD', label: "Andorra" },
  { value: "Angola", iso: 'AO', label: "Angola" },
  { value: "Antigua y Barbuda", iso: 'AG', label: "Antigua & Barbuda" },
  { value: "Argentina", iso: 'AR', label: "Argentina" },
  { value: "Armenia", iso: 'AM', label: "Armenia" },
  { value: "Australia", iso: 'AU', label: "Australia" },
  { value: "Austria", iso: 'AT', label: "Austria" },
  { value: "Azerbaiyán", iso: 'AZ', label: "Azerbaijan" },
  { value: "Bahamas", iso: 'BS', label: "Bahamas" },
  { value: "Baréin", iso: 'BH', label: "Bahrain" },
  { value: "Bangladés", iso: 'BD', label: "Bangladesh" },
  { value: "Barbados", iso: 'BB', label: "Barbados" },
  { value: "Bielorrusia", iso: 'BY', label: "Belarus" },
  { value: "Bélgica", iso: 'BE', label: "Belgium" },
  { value: "Belice", iso: 'BZ', label: "Belize" },
  { value: "Benín", iso: 'BJ', label: "Benin" },
  { value: "Bután", iso: 'BT', label: "Bhutan" },
  { value: "Bolivia", iso: 'BO', label: "Bolivia" },
  { value: "Bosnia y Herzegovina", iso: 'BA', label: "Bosnia & Herzegovina" },
  { value: "Botsuana", iso: 'BW', label: "Botswana" },
  { value: "Brasil", iso: 'BR', label: "Brazil" },
  { value: "Brunéi", iso: 'BN', label: "Brunei" },
  { value: "Bulgaria", iso: 'BG', label: "Bulgaria" },
  { value: "Burkina Faso", iso: 'BF', label: "Burkina Faso" },
  { value: "Burundi", iso: 'BI', label: "Burundi" },
  { value: "Cabo Verde", iso: 'CV', label: "Cape Verde" },
  { value: "Camboya", iso: 'KH', label: "Cambodia" },
  { value: "Camerún", iso: 'CM', label: "Cameroon" },
  { value: "Canadá", iso: 'CA', label: "Canada" },
  { value: "República Centroafricana", iso: 'CF', label: "Central African Republic" },
  { value: "Chad", iso: 'TD', label: "Chad" },
  { value: "Chile", iso: 'CL', label: "Chile" },
  { value: "China", iso: 'CN', label: "China" },
  { value: "Colombia", iso: 'CO', label: "Colombia" },
  { value: "Comoras", iso: 'KM', label: "Comoros" },
  { value: "Congo", iso: 'CG', label: "Congo - Brazzaville" },
  { value: "Costa de Marfil", iso: 'CI', label: "Côte d’Ivoire" },
  { value: "Costa Rica", iso: 'CR', label: "Costa Rica" },
  { value: "Croacia", iso: 'HR', label: "Croatia" },
  { value: "Cuba", iso: 'CU', label: "Cuba" },
  { value: "Chipre", iso: 'CY', label: "Cyprus" },
  { value: "República Checa", iso: 'CZ', label: "Czechia" },
  { value: "Dinamarca", iso: 'DK', label: "Denmark" },
  { value: "Yibuti", iso: 'DJ', label: "Djibouti" },
  { value: "Dominica", iso: 'DM', label: "Dominica" },
  { value: "República Dominicana", iso: 'DO', label: "Dominican Republic" },
  { value: "Ecuador", iso: 'EC', label: "Ecuador" },
  { value: "Egipto", iso: 'EG', label: "Egypt" },
  { value: "El Salvador", iso: 'SV', label: "El Salvador" },
  { value: "Guinea Ecuatorial", iso: 'GQ', label: "Equatorial Guinea" },
  { value: "Eritrea", iso: 'ER', label: "Eritrea" },
  { value: "Estonia", iso: 'EE', label: "Estonia" },
  { value: "Esuatini", iso: 'SZ', label: "Eswatini" },
  { value: "Etiopía", iso: 'ET', label: "Ethiopia" },
  { value: "Fiyi", iso: 'FJ', label: "Fiji" },
  { value: "Finlandia", iso: 'FI', label: "Finland" },
  { value: "Francia", iso: 'FR', label: "France" },
  { value: "Gabón", iso: 'GA', label: "Gabon" },
  { value: "Gambia", iso: 'GM', label: "Gambia" },
  { value: "Georgia", iso: 'GE', label: "Georgia" },
  { value: "Alemania", iso: 'DE', label: "Germany" },
  { value: "Ghana", iso: 'GH', label: "Ghana" },
  { value: "Grecia", iso: 'GR', label: "Greece" },
  { value: "Granada", iso: 'GD', label: "Grenada" },
  { value: "Guatemala", iso: 'GT', label: "Guatemala" },
  { value: "Guinea", iso: 'GN', label: "Guinea" },
  { value: "Guinea-Bisáu", iso: 'GW', label: "Guinea-Bissau" },
  { value: "Guyana", iso: 'GY', label: "Guyana" },
  { value: "Haití", iso: 'HT', label: "Haiti" },
  { value: "Honduras", iso: 'HN', label: "Honduras" },
  { value: "Hungría", iso: 'HU', label: "Hungary" },
  { value: "Islandia", iso: 'IS', label: "Iceland" },
  { value: "India", iso: 'IN', label: "India" },
  { value: "Indonesia", iso: 'ID', label: "Indonesia" },
  { value: "Irán", iso: 'IR', label: "Iran" },
  { value: "Irak", iso: 'IQ', label: "Iraq" },
  { value: "Irlanda", iso: 'IE', label: "Ireland" },
  { value: "Israel", iso: 'IL', label: "Israel" },
  { value: "Italia", iso: 'IT', label: "Italy" },
  { value: "Jamaica", iso: 'JM', label: "Jamaica" },
  { value: "Japón", iso: 'JP', label: "Japan" },
  { value: "Jordania", iso: 'JO', label: "Jordan" },
  { value: "Kazajistán", iso: 'KZ', label: "Kazakhstan" },
  { value: "Kenia", iso: 'KE', label: "Kenya" },
  { value: "Kiribati", iso: 'KI', label: "Kiribati" },
  { value: "Kuwait", iso: 'KW', label: "Kuwait" },
  { value: "Kirguistán", iso: 'KG', label: "Kyrgyzstan" },
  { value: "Laos", iso: 'LA', label: "Laos" },
  { value: "Letonia", iso: 'LV', label: "Latvia" },
  { value: "Líbano", iso: 'LB', label: "Lebanon" },
  { value: "Lesoto", iso: 'LS', label: "Lesotho" },
  { value: "Liberia", iso: 'LR', label: "Liberia" },
  { value: "Libia", iso: 'LY', label: "Libya" },
  { value: "Liechtenstein", iso: 'LI', label: "Liechtenstein" },
  { value: "Lituania", iso: 'LT', label: "Lithuania" },
  { value: "Luxemburgo", iso: 'LU', label: "Luxembourg" },
  { value: "Madagascar", iso: 'MG', label: "Madagascar" },
  { value: "Malaui", iso: 'MW', label: "Malawi" },
  { value: "Malasia", iso: 'MY', label: "Malaysia" },
  { value: "Maldivas", iso: 'MV', label: "Maldives" },
  { value: "Malí", iso: 'ML', label: "Mali" },
  { value: "Malta", iso: 'MT', label: "Malta" },
  { value: "Islas Marshall", iso: 'MH', label: "Marshall Islands" },
  { value: "Mauritania", iso: 'MR', label: "Mauritania" },
  { value: "Mauricio", iso: 'MU', label: "Mauritius" },
  { value: "México", iso: 'MX', label: "Mexico" },
  { value: "Estados Federados de Micronesia", iso: 'FM', label: "Micronesia" },
  { value: "Moldavia", iso: 'MD', label: "Moldova" },
  { value: "Mónaco", iso: 'MC', label: "Monaco" },
  { value: "Mongolia", iso: 'MN', label: "Mongolia" },
  { value: "Montenegro", iso: 'ME', label: "Montenegro" },
  { value: "Marruecos", iso: 'MA', label: "Morocco" },
  { value: "Mozambique", iso: 'MZ', label: "Mozambique" },
  { value: "Birmania", iso: 'MM', label: "Myanmar (Burma)" },
  { value: "Namibia", iso: 'NA', label: "Namibia" },
  { value: "Nauru", iso: 'NR', label: "Nauru" },
  { value: "Nepal", iso: 'NP', label: "Nepal" },
  { value: "Países Bajos", iso: 'NL', label: "Netherlands" },
  { value: "Nueva Zelanda", iso: 'NZ', label: "New Zealand" },
  { value: "Nicaragua", iso: 'NI', label: "Nicaragua" },
  { value: "Níger", iso: 'NE', label: "Niger" },
  { value: "Nigeria", iso: 'NG', label: "Nigeria" },
  { value: "Corea del Norte", iso: 'KP', label: "North Korea" },
  { value: "Macedonia del Norte", iso: 'MK', label: "North Macedonia" },
  { value: "Noruega", iso: 'NO', label: "Norway" },
  { value: "Omán", iso: 'OM', label: "Oman" },
  { value: "Pakistán", iso: 'PK', label: "Pakistan" },
  { value: "Palaos", iso: 'PW', label: "Palau" },
  { value: "Panamá", iso: 'PA', label: "Panama" },
  { value: "Papúa Nueva Guinea", iso: 'PG', label: "Papua New Guinea" },
  { value: "Paraguay", iso: 'PY', label: "Paraguay" },
  { value: "Perú", iso: 'PE', label: "Peru" },
  { value: "Filipinas", iso: 'PH', label: "Philippines" },
  { value: "Polonia", iso: 'PL', label: "Poland" },
  { value: "Portugal", iso: 'PT', label: "Portugal" },
  { value: "Catar", iso: 'QA', label: "Qatar" },
  { value: "Rumanía", iso: 'RO', label: "Romania" },
  { value: "Federación Rusa", iso: 'RU', label: "Russia" },
  { value: "Ruanda", iso: 'RW', label: "Rwanda" },
  { value: "San Cristóbal y Nieves", iso: 'KN', label: "St. Kitts & Nevis" },
  { value: "Santa Lucía", iso: 'LC', label: "St. Lucia" },
  { value: "San Vicente y las Granadinas", iso: 'VC', label: "St. Vincent & Grenadines" },
  { value: "Samoa", iso: 'WS', label: "Samoa" },
  { value: "San Marino", iso: 'SM', label: "San Marino" },
  { value: "Santo Tomé y Príncipe", iso: 'ST', label: "São Tomé & Príncipe" },
  { value: "Arabia Saudita", iso: 'SA', label: "Saudi Arabia" },
  { value: "Senegal", iso: 'SN', label: "Senegal" },
  { value: "Serbia", iso: 'RS', label: "Serbia" },
  { value: "Seychelles", iso: 'SC', label: "Seychelles" },
  { value: "Sierra Leona", iso: 'SL', label: "Sierra Leone" },
  { value: "Singapur", iso: 'SG', label: "Singapore" },
  { value: "Eslovaquia", iso: 'SK', label: "Slovakia" },
  { value: "Eslovenia", iso: 'SI', label: "Slovenia" },
  { value: "Islas Salomón", iso: 'SB', label: "Solomon Islands" },
  { value: "Somalia", iso: 'SO', label: "Somalia" },
  { value: "Sudáfrica", iso: 'ZA', label: "South Africa" },
  { value: "Sudán del Sur", iso: 'SS', label: "South Sudan" },
  { value: "España", iso: 'ES', label: "Spain" },
  { value: "Sri Lanka", iso: 'LK', label: "Sri Lanka" },
  { value: "Sudán", iso: 'SD', label: "Sudan" },
  { value: "Surinam", iso: 'SR', label: "Suriname" },
  { value: "Suecia", iso: 'SE', label: "Sweden" },
  { value: "Suiza", iso: 'CH', label: "Switzerland" },
  { value: "Siria", iso: 'SY', label: "Syria" },
  { value: "Tayikistán", iso: 'TJ', label: "Tajikistan" },
  { value: "Tailandia", iso: 'TH', label: "Thailand" },
  { value: "Timor-Leste", iso: 'TL', label: "Timor-Leste" },
  { value: "Togo", iso: 'TG', label: "Togo" },
  { value: "Tonga", iso: 'TO', label: "Tonga" },
  { value: "Trinidad y Tobago", iso: 'TT', label: "Trinidad & Tobago" },
  { value: "Túnez", iso: 'TN', label: "Tunisia" },
  { value: "Turquía", iso: 'TR', label: "Türkiye" },
  { value: "Turkmenistán", iso: 'TM', label: "Turkmenistan" },
  { value: "Tuvalu", iso: 'TV', label: "Tuvalu" },
  { value: "Uganda", iso: 'UG', label: "Uganda" },
  { value: "Ucrania", iso: 'UA', label: "Ukraine" },
  { value: "Emiratos Árabes Unidos", iso: 'AE', label: "United Arab Emirates" },
  { value: "Reino Unido", iso: 'GB', label: "United Kingdom" },
  { value: "República Unida de Tanzania", iso: 'TZ', label: "Tanzania" },
  { value: "Estados Unidos de América", iso: 'US', label: "United States" },
  { value: "Uruguay", iso: 'UY', label: "Uruguay" },
  { value: "Uzbekistán", iso: 'UZ', label: "Uzbekistan" },
  { value: "Vanuatu", iso: 'VU', label: "Vanuatu" },
  { value: "Venezuela", iso: 'VE', label: "Venezuela" },
  { value: "Vietnam", iso: 'VN', label: "Vietnam" },
  { value: "Yemen", iso: 'YE', label: "Yemen" },
  { value: "Zambia", iso: 'ZM', label: "Zambia" },
  { value: "Zimbabue", iso: 'ZW', label: "Zimbabwe" },
  { value: "Taiwán", iso: 'TW', label: "Taiwan" },
];

export const CountryISO: Record<string, string> = Object.fromEntries(countries.flatMap(c => [[c.value, c.iso], [c.label, c.iso]]));
const labels: Record<string, string> = Object.fromEntries(countries.map(c => [c.value, c.label]));
export const countryLabel = (value: string) => labels[value] || value;
