import React, { useCallback, useState } from 'react';
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import API from '../api/api';
import { CenterClient } from '../types';

export default function CenterClientsScreen({ navigation }: any) {
  const [clients, setClients] = useState<CenterClient[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { try { setError(''); const response = await API.get<CenterClient[]>('/center/clients'); setClients(Array.isArray(response.data) ? response.data : []); } catch (err: any) { setError(err?.response?.data?.message || 'Could not load center clients.'); } finally { setLoading(false); setRefreshing(false); } }, []);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const visible = clients.filter((client) => `${client.name} ${client.email}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));
  return <View style={styles.screen}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); load(); }} />}><Text style={styles.eyebrow}>CENTER RELATIONSHIPS</Text><Text style={styles.title}>Your clients</Text><Text style={styles.subtitle}>Divers who appear in dives linked to this center.</Text><TextInput accessibilityLabel="Search clients" value={query} onChangeText={setQuery} placeholder="Search clients" style={styles.search} />{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}{loading ? <ActivityIndicator color="#0077CC" style={styles.loader} /> : visible.length ? <View style={styles.list}>{visible.map((client) => <TouchableOpacity key={client.id} accessibilityRole="button" style={styles.card} onPress={() => navigation.navigate('Profile', { userId: client.id })}><View style={styles.avatar}><Text style={styles.avatarText}>{client.name.slice(0, 1).toUpperCase()}</Text></View><View style={styles.copy}><Text style={styles.name}>{client.name}</Text><Text style={styles.email}>{client.email}</Text><Text style={styles.meta}>{client.dives} linked dive{client.dives === 1 ? '' : 's'}{client.lastDive ? ` · Last ${new Date(client.lastDive).toLocaleDateString()}` : ''}</Text></View><Text style={styles.arrow}>›</Text></TouchableOpacity>)}</View> : <View style={styles.empty}><Text style={styles.emptyTitle}>{clients.length ? 'No clients match' : 'No clients yet'}</Text><Text style={styles.emptyText}>{clients.length ? 'Try another search.' : 'Link a dive center to a dive to start building your client list.'}</Text></View>}</ScrollView></View>;
}

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#f3f6f8' }, content: { width: '100%', maxWidth: 900, alignSelf: 'center', padding: 20, paddingBottom: 50 }, eyebrow: { color: '#0b777b', fontSize: 11, fontWeight: 'bold', letterSpacing: 1 }, title: { color: '#123b52', fontSize: 29, fontWeight: 'bold', marginTop: 5 }, subtitle: { color: '#607789', marginTop: 6 }, search: { minHeight: 46, backgroundColor: '#fff', borderWidth: 1, borderColor: '#aabfc7', borderRadius: 12, paddingHorizontal: 13, marginTop: 18, color: '#334155' }, error: { color: '#b42318', marginTop: 12 }, loader: { marginTop: 30 }, list: { gap: 10, marginTop: 18 }, card: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', borderWidth: 1, borderColor: '#ccdbe0', borderRadius: 16, padding: 14 }, avatar: { width: 42, height: 42, borderRadius: 21, backgroundColor: '#dfecef', alignItems: 'center', justifyContent: 'center', marginRight: 12 }, avatarText: { color: '#123b52', fontWeight: 'bold', fontSize: 17 }, copy: { flex: 1, minWidth: 0 }, name: { color: '#123b52', fontSize: 16, fontWeight: 'bold' }, email: { color: '#607789', fontSize: 12, marginTop: 2 }, meta: { color: '#0b777b', fontSize: 11, marginTop: 6 }, arrow: { color: '#0b777b', fontSize: 27, marginLeft: 10 }, empty: { backgroundColor: '#fff', borderRadius: 16, alignItems: 'center', padding: 30, marginTop: 18 }, emptyTitle: { color: '#123b52', fontSize: 18, fontWeight: 'bold' }, emptyText: { color: '#718394', textAlign: 'center', marginTop: 6 } });
